openstack_connection:
  host: 0.0.0.0
  # Client Port
  port: 9090
  # Gateway IP
  gateway_ip: 129.70.51.75
  # If set to True the client will use a Gateway instead of providing floating IPs for each instance.
  use_gateway: True

  set_password: False
  # network where the project is located
  network: portalexternalnetwork

  # subnetwork for starting Clusters
  sub_network: portalexternalsubnetwork



  floating_ip_network: external
  # The name of the availability zone the server should be placed.
  availability_zone: default
  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem

  # Used for gateway port calculation , x is always the last octet of the fixed ip (example : (x + 3) *3 ) )
  ssh_port_calc_formular: 30000 + x
  udp_port_calc_formular: x * 10 +  30000

bibigrid:
  # Url for Bibigrid API
  bibigrid_url: https://172.21.0.1:8443/bibigrid/
  sub_network: portalexternalsubnetwork
forc:
  forc_url: https://proxy-dev.bi.denbi.de:5000/
