redis:
  host: client_redis
  port: 6379
  password: ""

openstack_connection:
  gateway_security_group_id: e75f0abb-bd9d-4bda-afc7-cef1ad459eee

  threads: 30
  host: 0.0.0.0
  # Client Port
  port: 9090
  # Gateway IP
  gateway_ip: 129.70.51.75
  # If set to True the client will use a Gateway instead of providing floating IPs for each instance.
  use_gateway: True

  set_password: False
  # network where the project is located
  network: portalexternalnetwork

  # subnetwork for starting Clusters
  sub_network: portalexternalsubnetwork

  production: False



  floating_ip_network: external
  # If you use docker-compose this path needs to be the path you mount the server.pem into
  certfile: /code/VirtualMachineService/keys/server.pem
  ca_certs_path: /code/VirtualMachineService/keys/CA.pem
  use_ssl: True

  # Used for gateway port calculation , x is always the last octet of the fixed ip (example : (x + 3) *3 ) )
  ssh_port_calc_formular: 30000 + x + y * 256
  udp_port_calc_formular: 30000 + x + y * 256

bibigrid:
  # Url for Bibigrid API
    port: 8080
    host: bibigrid
    https: False
    localDnsLookup: False
    sub_network: portalexternalsubnetwork
    bibigrid_modes:
      -   slurm
    ansibleGalaxyRoles:
                   - name: autoscaling
                     hosts: master
                     git: https://github.com/patricS4/autoscaling-config-ansible


forc:
  forc_url:
  openresty_url: 
  forc_https: True
  github_playbooks_repo:
  forc_remote_id:


cloud_site: bielefeld
