openstack_connection:
    host: 0.0.0.0
    port: 9090
    gateway_base: 30000
    gateway_ip: 172.21.40.14
    use_gateway: True
    set_password: False
    network: portalnetzwerk
    tag: portalclient
    floating_ip_network: cebitec
    availability_zone: default
    # If you use docker-compose this path needs to be the path you mount the server.pem into
    certfile: /code/VirtualMachineService/keys/server.pem

        
