version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target_branch: "dev"
    reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"

