version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
    commit_message:
      prefix: "feat"
      include_scope: true

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
    commit_message:
      prefix: "feat"
      include_scope: true


