version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"


