version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "deNBI/portal-dev"
      commit-message:
        prefix: "feat"
        include: "scope"
      open-pull-requests-limit: 15

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
    commit-message:
      prefix: "feat"
      include: "scope"
    open-pull-requests-limit: 15

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
    commit-message:
      prefix: "feat"
      include: "scope"
    open-pull-requests-limit: 15

  - package-ecosystem: "docker"
    directory: "/Dockerfile.update"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    reviewers:
      - "deNBI/portal-dev"
    commit-message:
      prefix: "feat"
      include: "scope"
    open-pull-requests-limit: 15


