exclude: "^docs/|/migrations/"
default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: upgrade-type-hints

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [-h , --disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ "--config=setup.cfg" ]
        additional_dependencies: [ flake8-isort ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
