version: '3.5'
services:
  portal-client:
    build:
       context: .
       dockerfile: Dockerfile
    ports:
     - "9090:9090"
    environment:
     - OS_AUTH_URL
     - OS_PROJECT_ID
     - OS_PROJECT_NAME
     - OS_USERNAME
     - OS_PASSWORD
     - OS_USER_DOMAIN_NAME
    command: python3 VirtualMachineServer.py
