version: '3.5'
services:
  portal-client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:9090
    env_file:
      - .env
    volumes:
      - ./VirtualMachineService/config/config_local.yml:/code/VirtualMachineService/config.yml
      - ./VirtualMachineService/keys/localhost/server.pem:/code/VirtualMachineService/keys/server.pem
    command: python3 VirtualMachineServer.py /code/VirtualMachineService/config.yml
    networks:
      - portal

  client_redis:
    container_name: client_redis
    image: redis:7.0.7
    expose:
      - "6379"
    networks:
      - portal

networks:
  portal:
    name: portal_default
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
