version: '3.5'
services:
  portal-client:
    container_name: client
    image: denbicloud/cloud-portal-client:${CLOUD_PORTAL_CLIENT_TAG}
    ports:
      - ${CLIENT_PORT}:9090
    env_file:
      - .env
    volumes:
      -  ${client_PERSISTENT_PATH}/config.yml:/code/VirtualMachineService/config.yml
      -  ${client_PERSISTENT_PATH}/server.pem:/code/VirtualMachineService/keys/server.pem
      - ./logs/client:/code/VirtualMachineService/log:rw
    command: python3 VirtualMachineServer.py /code/VirtualMachineService/config.yml
    networks:
     - portal

  client_redis:
    container_name: client_redis
    image: redis:6.2.6
    expose:
      - "6379"
    networks:
      - portal

  # filebeat
  filebeat:
    container_name: client_filebeat
    image: docker.elastic.co/beats/filebeat:7.16.2
    env_file:
      - .env
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/log:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: [sh, -c, "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat run -e"]
    networks:
      - portal

networks:
  portal:
    name: portal_default
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1440
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1440
