version: '3.5'
services:
  portal-client:
    build:
       context: .
       dockerfile: Dockerfile
    ports:
     - ${CLIENT_PORT}:9090

    env_file:
        - .env
        - config/.env_local
    volumes:
      - ./VirtualMachineService/config/local_config.yml:/code/VirtualMachineService/local_config.yml
      - ./VirtualMachineService/keys/localhost/server.pem:/code/VirtualMachineService/keys/server.pem
    command: python3 VirtualMachineServer.py /code/VirtualMachineService/local_config.yml
    networks:
     - portal

  redis:
    image: redis:6.0.9
    expose:
      - "6379"
    networks:
      - portal


networks:
  portal:
    name: portal_default
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
