roles:
  - name: oefenweb.rstudio_server
    version: v3.0.3

  - name: oefenweb.latest_r
    version: v3.1.4


  - name: andrewrothstein.miniconda
    version: v6.1.7

  - name: andrewrothstein.conda-env
