roles:
  - name: oefenweb.rstudio_server
    version: v2.7.1

  - name: oefenweb.latest_r
    version: v3.1.1


  - name: andrewrothstein.miniconda
    version: v6.1.6

  - name: andrewrothstein.conda-env
