roles:
  - name: oefenweb.rstudio_server
    version: v4.1.0

  - name: oefenweb.latest_r
    version: v3.1.4


  - name: andrewrothstein.miniconda
    version: v6.1.9

  - name: andrewrothstein.conda-env
