- name: Download miniconda install script
  get_url:
  args:
    url: "{{ bioconda_folders.conda_installer_url }}"
    dest: "{{ bioconda_folders.install_script }}"
    mode: 0755
    timeout: 180

- name: Install miniconda
  shell: "timeout 3m {{ bioconda_folders.install_script }} -b"
  args:
    executable: /bin/bash
    creates: "{{ bioconda_folders.conda_dir }}"

- name: Add channels
  shell: "timeout 2m bash -c 'source {{ bioconda_folders.conda_dir }}/bin/activate && conda config --add channels default && conda config --add channels bioconda && conda config --add channels conda-forge'"
  args:
    executable: /bin/bash

- name: Create environment
  shell: "timeout 2m bash -c 'source {{ bioconda_folders.conda_dir }}/bin/activate && conda create --yes -n {{ bioconda_tools.env }}'"
  args:
    executable: /bin/bash

- name: Install chosen packages
  shell: "timeout {{ bioconda_tools.timeout_length }} bash -c 'source {{ bioconda_folders.conda_dir }}/bin/activate && conda activate {{ bioconda_tools.env }} && conda install --yes {{ bioconda_tools.string_line }}'"
  args:
    executable: /bin/bash
