from enum import Enum


class VmTaskStates(Enum):
    SUSPENDING = "SUSPENDING"
    PREPARE_PLAYBOOK_BUILD = "PREPARE_PLAYBOOK_BUILD"
    BUILD_PLAYBOOK = "BUILD_PLAYBOOK"
    PLAYBOOK_FAILED = "PLAYBOOK_FAILED"
    PLAYBOOK_SUCCESSFUL = "PLAYBOOK_SUCCESSFUL"
    CHECKING_SSH_CONNECTION = "CHECKING_SSH_CONNECTION"


class VmStates(Enum):
    BUILD = "BUILD"
    ACTIVE = "ACTIVE"
    ERROR = "ERROR"
    SHUTOFF = "SHUTOFF"
    NOT_FOUND = "NOT_FOUND"
    PORT_CLOSED = "PORT_CLOSED"
