- name: Setup and install Basics
  hosts: all
  become: yes
  vars_files:
    - general_variables.yml
  
  roles:
    - role: geerlingguy.docker
      
  pre_tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7"L
          
  tasks:
    - name: Update cache
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Checkout cloud-portal-client repository
      git:
        repo: "git@github.com:deNBI/cloud-portal-client.git"
        dest: "{{ client.REPO_PATH }}"
        accept_hostkey: yes
        force: yes
        version: "{{ repo_version | default('master') }}"
      become: no

    - name: Install python3-pip
      apt:
        state: latest
        name: python3-pip
        
    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - libffi-dev 
        - libssl-dev
        - jq

    - name: Install docker-compose with pip
      pip:
        name: docker-compose
        
    - name: Create variable files
      copy: 
        content: "{{ item.content | dict2items | map('to_json') | map('regex_replace', '\"key\":\\s\"(.*)\"', lookup('vars', 'regex_env')) | map('from_json') | list}}"
        dest: "{{ client.REPO_PATH }}/.ansible_environment_{{ item.name }}.json"
        backup: yes
      vars:
        regex_env: "\"key\": \"{{ item.name }}_\\1\""
      with_items:
        - { content: "{{ client }}", name: 'client' }

    - name: Transform json to properties file
      shell: rm -f "{{ client.REPO_PATH }}"/.ansible_environment && jq -r '.[]|"\(.key)=\(.value)"' "{{ client.REPO_PATH }}"/.ansible_environment_*.json >> "{{ client.REPO_PATH }}"/.ansible_environment

    - name: Append secrets to env file
      shell: cat "{{ client.REPO_PATH }}"/.secrets "{{ client.REPO_PATH }}"/.ansible_environment >> "{{ client.REPO_PATH }}"/.env
