- name: Setting up gateway
  hosts: all
  become: yes
  vars_files:
    - gateway-setup-variables.yml
    - general_variables.yml

  tasks:

    - name: Create persistent gateway script directorie
      file:
        path: "{{ gateway.SCRIPT_PERSISTENT_PATH }}"
        state: directory
      tags: [ 'never', 'gateway' ]



    - name: Copy TCP script from repository
      copy:
        src: "{{ client.REPO_PATH }}/scripts/gateway/{{ gateway.TCP_SCRIPT_PERSISTENT_NAME }}"
        dest: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.TCP_SCRIPT_PERSISTENT_NAME }}"
        mode: 0774
        remote_src: yes
      when: tcp_script_in is not defined
      tags: [ 'never', 'gateway' ]



    - name: Copy UDP script from repository
      copy:
        src: "{{ client.REPO_PATH }}/scripts/gateway/{{ gateway.UDP_SCRIPT_PERSISTENT_NAME }}"
        dest: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.UDP_SCRIPT_PERSISTENT_NAME }}"
        mode: 0774
        remote_src: yes
      when: udp_script_in is not defined
      tags: [ 'never', 'gateway' ]


    - name: Copy specified TCP script
      copy:
        src: "{{ tcp_script_in }}"
        dest: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.TCP_SCRIPT_PERSISTENT_NAME }}"
        mode: 0774
      when: tcp_script_in is defined
      tags: [ 'never', 'gateway' ]


    - name: Copy specified UDP script
      copy:
        src: "{{ udp_script_in }}"
        dest: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.UDP_SCRIPT_PERSISTENT_NAME }}"
        mode: 0774
      when: udp_script_in is defined
      tags: [ 'never', 'gateway' ]


    - name: Run TCP script
      become: yes
      command: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.TCP_SCRIPT_PERSISTENT_NAME }}"
      tags: [ 'never', 'gateway' ]


    - name: Run UDP script
      become: yes
      command: "{{ gateway.SCRIPT_PERSISTENT_PATH }}/{{ gateway.UDP_SCRIPT_PERSISTENT_NAME }}"
      tags: [ 'never', 'gateway' ]


    - name: Install IPtables-persistent
      apt:
        name:
          - iptables-persistent
        update_cache: yes
        state: present
      tags: [ 'never', 'gateway' ]
