- name: Setup and install Basics
  hosts: all
  become: yes
  vars_files:
    - general_variables.yml




  pre_tasks:
    - name: Verify Ansible version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7"L
      tags: always

    - name: Update cache
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: always


  tasks:
    - name: Checkout cloud-portal-client repository
      git:
        repo: "git@github.com:deNBI/cloud-portal-client.git"
        dest: "{{ client.REPO_PATH }}"
        accept_hostkey: yes
        force: yes
        version: "{{ repo_version | default('master') }}"
      become: no
      tags: always

    - name: Import deadsnake PPA for python3.8
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        update_cache: yes
      tags: always

    - name: Install python3.8
      apt:
        state: latest
        name: python3.8
      tags: always

    - name: Install python3-pip
      apt:
        state: latest
        name: python3-pip
      tags: always

    - name: Install list of packages
      apt:
        name:  ['libffi-dev', 'libssl-dev', 'jq', 'python3-setuptools']
        state: present
        update_cache: yes
      tags: always

    - name: Install docker-compose with pip
      pip:
        name: docker-compose
      tags: always

    - name: Prune everything Docker (inlucding non-dangling images - except Volumes)
      community.docker.docker_prune:
        containers: yes
        images: yes
        images_filter:
          dangling: false
        networks: yes
