- name: Setup and install Basics
  hosts: all
  become: yes
  vars_files:
    - general_variables.yml
  
  roles:
    - role: geerlingguy.docker
      
  pre_tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7"L
          
  tasks:
    - name: Update cache
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Checkout cloud-portal-client repository
      git:
        repo: "git@github.com:deNBI/cloud-portal-client.git"
        dest: "{{ client.REPO_PATH }}"
        accept_hostkey: yes
        force: yes
        version: "{{ repo_version | default('master') }}"
      become: no

    - name: Install python3-pip
      apt:
        state: latest
        name: python3-pip
        
    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - libffi-dev 
        - libssl-dev
        - jq

    - name: Install docker-compose with pip
      pip:
        name: docker-compose
        
   
