version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "dev"
    default_reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "dev"
    default_reviewers:
      - "dweinholz"
      - "eKatchko"
      - "vktrrdk"

