---
# handlers file for guacamolerdp-ansible

- name: Restart xrdp
  systemd:
    name: xrdp
    state: restarted

- name: Restart guacd
  systemd:
    name: guacd
    state: restarted

- name: Restart Tomcat
  systemd:
    name: tomcat8
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: yes