

- name: Install needed libraries and tools
  apt:
    name:
      - make
      - gcc
      - vim
      - curl
      - wget
      - g++
      - libcairo2-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libtool-bin
      - libossp-uuid-dev
      - libavcodec-dev
      - libavutil-dev
      - libswscale-dev
      - build-essential
      - libpango1.0-dev
      - libssh2-1-dev
      - libvncserver-dev
      - libtelnet-dev
      - freerdp2-dev
      - libwebsockets-dev
      - libssl-dev
      - libvorbis-dev
      - libwebp-dev
      - tomcat9
      - tomcat9-admin
      - tomcat9-user
    state: latest

- name: Download guacamole src
  get_url:
    url: http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz
    dest: /usr/share/guacamole.tar.gz

- name: Download guacamole war file
  get_url:
    url: http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/1.4.0/binary/guacamole-1.4.0.war
    dest: /usr/share/guacamole.war

- name: Prepare build directory
  file:
    state: directory
    path: /usr/share/guacamole/

- name: Unarchive source files
  unarchive:
    remote_src: yes
    src: /usr/share/guacamole.tar.gz
    dest: /usr/share/guacamole

- name: Configure systemd unit
  shell: "./configure --with-systemd-dir=/etc/systemd/system"
  args:
    chdir: /usr/share/guacamole/guacamole-server-1.4.0/
    creates: /usr/share/guacamole/guacamole-server-1.4.0/Makefile

- name: Compile guacamole
  make:
    chdir: /usr/share/guacamole/guacamole-server-1.4.0/

- name: Make install
  make:
    chdir: /usr/share/guacamole/guacamole-server-1.4.0/
    target: install

- name: Link libraries
  shell: ldconfig
  args:
    chdir: /usr/share/guacamole/guacamole-server-1.4.0/

- name: Enable guacamole daemon
  systemd:
    name: guacd
    enabled: yes

- name: Create guacamole config folder
  file:
    state: directory
    path: /etc/guacamole

- name: Create guacamole.properties
  copy:
    src: guacamole.properties
    dest: /etc/guacamole/guacamole.properties
  notify: Restart guacd

- name: Generate guacamole mapping
  template:
    src: user-mapping.xml.j2
    dest: /etc/guacamole/user-mapping.xml
  notify: Restart guacd

- name: Register path in env
  lineinfile:
    path: /etc/environment
    line: 'GUACAMOLE_HOME="/etc/guacamole"'
    state: present

- name: Copy tomcat guacamole client
  copy:
    remote_src: yes
    src: /usr/share/guacamole.war
    dest: /var/lib/tomcat9/webapps/guacamole.war
  notify: Restart Tomcat

- name: Link configuration directory to tomcat
  file:
    state: link
    src: /etc/guacamole
    dest: /usr/share/tomcat9/.guacamole
  notify: Reload systemd
