- name: Disable periodic updates
  block:
    - name: Disable unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: "^APT::Periodic::Unattended-Upgrade"
        line: 'APT::Periodic::Unattended-Upgrade "0";'
        create: yes
    - name: Stop apt-daily.* systemd services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily.timer
        - apt-daily-upgrade
        - apt-daily-upgrade.timer

- name: Update apt cache
  apt:
    update_cache: true
  become: yes

- name: Wait for automatic system updates 1
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;

- name: Wait for automatic system updates 2
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;

- name: Install docker.io package
  apt:
    name: docker.io
  become: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes

- name: Install docker python dev package
  apt:
    name: python3-docker
  become: yes

- name: Ensure data path exists
  file:
    state: directory
    path: "{{ cwlab_vars.data_volume_path }}"
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Launch cwlab container
  community.general.docker_container:
    name: cwlab
    image: "{{ cwlab_vars.image }}"
    ports:
      - "{{ cwlab_vars.exposed_port }}:5000"
    volumes:
      - "{{ cwlab_vars.data_volume_path }}:/cwlab"
    restart_policy: always
    user: 1000:1000
    recreate: yes
    privileged: yes
    working_dir: "/cwlab"
    container_default_behavior: no_defaults

- name: Enable periodic updates
  block:
    - name: enable unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: "^APT::Periodic::Unattended-Upgrade"
        line: 'APT::Periodic::Unattended-Upgrade "1";'
        create: yes
    - name: Start apt-daily.* systemd services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily.timer
        - apt-daily-upgrade
        - apt-daily-upgrade.timer
