- name: Disable periodic updates
  block:
    - name: Disable unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: "^APT::Periodic::Unattended-Upgrade"
        line: 'APT::Periodic::Unattended-Upgrade "0";'
        create: yes
    - name: Stop apt-daily.* systemd services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily.timer
        - apt-daily-upgrade.timer

- name: Wait for automatic system updates 1
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
  when: rstudio_vars.create_only_backend == "false"

- name: Wait for automatic system updates 2
  shell: while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;
  when: rstudio_vars.create_only_backend == "false"

- name: Setup password for default user
  user:
    name: "{{ rstudio_vars.DEFAULT_USER }}"
    password: "{{ rstudio_vars.DEFAULT_PASSWORD_HASHED }}"

- name: Install R role
  include_role:
    name: oefenweb.r
  when: rstudio_vars.create_only_backend == "false"

- name: Install rstudio-server role
  include_role:
    name: oefenweb.rstudio_server
  vars:
    rstudio_install: [r-base]
  when: rstudio_vars.create_only_backend == "false"

- name: Copy session file if also installing rstudio
  copy:
    content: "session-timeout-minutes=180"
    dest: "{{ rstudio_vars.RSESSION_FILE_PATH }}"
    mode: "0644"
    owner: "root"
    group: "root"
  when: rstudio_vars.create_only_backend == "false"

- name: Flush rstudio handlers
  meta: flush_handlers
  when: rstudio_vars.create_only_backend == "false"

- name: Enable periodic updates
  block:
    - name: enable unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: "^APT::Periodic::Unattended-Upgrade"
        line: 'APT::Periodic::Unattended-Upgrade "1";'
        create: yes
    - name: Start apt-daily.* systemd services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily.timer
        - apt-daily-upgrade.timer
