name: Create Release Image
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
     - name: Get the version
       id: get_version
       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
     - uses: actions/checkout@v3.3.0
     - name: Publish to Registry
       uses: elgohr/Publish-Docker-Github-Action@master
       with:
        name: denbicloud/cloud-portal-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: ${{ steps.get_version.outputs.VERSION }}
