name: Spellchecking
on: push
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checking out Branch
        run: git checkout "${GITHUB_REF:11}"
      - name: own iml
        run: |
          curl -L -o ./install-misspell.sh https://git.io/misspell
          sh ./install-misspell.sh
          rm install-misspell.sh
          ./bin/misspell -w 
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         commit-message: fix(Linting):blacked code
         title: Automated Spellchecking 
         body: |
                        New Spellchecking
                        - Fixed spelling errors
                        - Auto-generated by [create-pull-request][1]
                        [1]: https://github.com/peter-evans/create-pull-request
         labels: automated,linting
         reviewers: ${{github.actor}}
         branch: fix(linting)_${{github.ref}}
      - name: Check outputs
        run: |
                      echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
                      echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
 
